import type { Metadata } from "next"
import { LegalShell } from "@/components/legal-shell"
export const metadata: Metadata = { title: "Confidentialité et données personnelles", alternates: { canonical: "/confidentialite" } }

export default function Page() {
  return <LegalShell title="Confidentialité">
    <section><h2>Qui traite vos données ?</h2><p>Dylan Clochard est le point de contact et responsable des traitements liés à ce portfolio. Vous pouvez le joindre à <a href="mailto:dylanclochard@gmail.com">dylanclochard@gmail.com</a>.</p></section>
    <section><h2>Consulter le portfolio</h2><p>Le site ne comporte pas de compte, de formulaire, de publicité, de pixel de suivi ni de script de mesure d’audience. Les images des projets et les polices sont servies par le site.</p><p>L’hébergement nécessite le traitement de données techniques, notamment l’adresse IP, la date de requête, l’URL demandée et les informations du navigateur. Elles servent à délivrer les pages et à protéger le service, sur le fondement de l’intérêt légitime au fonctionnement et à la sécurité du site. Les journaux techniques relèvent des paramètres et obligations de l’hébergeur ; ils ne sont pas exploités par l’éditeur pour suivre votre parcours à des fins publicitaires.</p></section>
    <section><h2>Préférence de langue</h2><p>Lorsque vous changez de langue, la valeur « fr » ou « en » est enregistrée sous la clé « language » dans le stockage local de votre navigateur. Elle reste sur votre appareil jusqu’à son effacement et n’est pas envoyée à un outil statistique. Ce stockage de préférence permet de conserver votre choix ; aucun bandeau de consentement publicitaire n’est utilisé.</p><p>Vous pouvez supprimer cette préférence dans les réglages de données du site de votre navigateur. Le portfolio reste utilisable si le stockage est bloqué.</p></section>
    <section><h2>Prendre contact</h2><p>Les liens e-mail et téléphone ouvrent votre application habituelle. Aucun message n’est envoyé à votre insu par le site. Si vous contactez Dylan, vos coordonnées, le contenu de votre message et les éventuelles pièces jointes servent uniquement à répondre et à suivre l’échange, sur le fondement de l’intérêt légitime à traiter les sollicitations professionnelles.</p><p>La conservation prévue est limitée à 12 mois après le dernier échange, sauf relation qui se poursuit ou nécessité justifiée de conserver une preuve liée à un litige ou à une obligation légale. Les informations nécessaires dans ce dernier cas sont conservées séparément pour la durée applicable. Évitez de transmettre des données sensibles qui ne sont pas utiles à votre demande.</p></section>
    <section><h2>Destinataires et transferts</h2><p>Les échanges sont destinés à Dylan Clochard. Les prestataires techniques interviennent pour l’hébergement (Vercel) et la messagerie (Gmail, Google). Des traitements peuvent avoir lieu hors de l’Espace économique européen, notamment aux États-Unis. Les garanties et sous-traitants de l’hébergement sont décrits dans <a href="https://vercel.com/legal/dpa">l’accord de traitement des données de Vercel</a> ; ceux de la messagerie dans <a href="https://policies.google.com/privacy?hl=fr">la politique de Google</a>. Une copie ou des précisions sur les garanties applicables peuvent être demandées au contact du site.</p><p>Les liens vers GitHub, LinkedIn et les projets sont de simples liens externes : les règles de ces services s’appliquent lorsque vous les ouvrez. Aucune donnée n’est vendue par l’éditeur. Le site n’effectue ni profilage ni décision automatisée.</p></section>
    <section><h2>Vidéos des projets</h2><p>Les galeries proposent des vidéos YouTube. Avant votre autorisation, seules des captures locales sont affichées : aucun lecteur ni aperçu distant de YouTube n’est chargé. Le bouton « Autoriser YouTube et lire la vidéo » active un lecteur du domaine youtube-nocookie.com. Google reçoit alors notamment votre adresse IP et des données de lecture, et peut utiliser des traceurs selon ses règles. Ce chargement repose sur votre consentement.</p><p>Le choix n’est pas mémorisé entre les ouvertures de la galerie. Vous pouvez arrêter et désactiver le lecteur, passer aux captures ou fermer la galerie à tout moment ; cela retire le lecteur et arrête ses nouvelles connexions, sans effacer les données déjà reçues par Google. Les règles de conservation, de transfert et les moyens d’exercice des droits sont décrits dans <a href="https://policies.google.com/privacy?hl=fr">la politique de Google</a>. Vous pouvez consulter toutes les captures sans autoriser YouTube.</p></section>
    <section><h2>Vos droits</h2><p>Selon les conditions prévues par le RGPD, vous pouvez demander l’accès, la rectification, l’effacement ou la limitation du traitement de vos données. Vous pouvez vous opposer aux traitements fondés sur l’intérêt légitime, pour des raisons tenant à votre situation. La portabilité s’applique aux traitements automatisés fondés sur le consentement ou le contrat lorsqu’ils existent. Vous pouvez également donner des directives sur le sort de vos données après votre décès.</p><p>Adressez votre demande à <a href="mailto:dylanclochard@gmail.com?subject=Donn%C3%A9es%20personnelles">dylanclochard@gmail.com</a>. Une réponse doit être apportée sous un mois, avec prolongation motivée possible dans les cas prévus par le RGPD. Un justificatif d’identité ne sera demandé qu’en cas de doute raisonnable. Vous pouvez déposer une réclamation auprès de la <a href="https://www.cnil.fr/fr/adresser-une-plainte">CNIL</a>, sans devoir nous contacter au préalable.</p></section>
  </LegalShell>
}
